/** derivative.h
 * This file includes the CMSIS <device>.h header for the
 * MCU used in this project.
 * 
 * This file is provided by the MSF, unlike the "derivative.h" file 
 * generated by CodeWarrior project wizard, which includes the <device>.h
 *  file for the EWL library used by CW rather than the CMSIS file.  
 *  
 * This file is for MKL25Z4 device     
*/

#ifndef MSF_KINETIS_DERIVATIVE_H
    #define MSF_KINETIS_DERIVATIVE_H

#include "MKL25Z4.h"

#endif // MSF_KINETIS_DERIVATIVE_H
